# Setup
title:        Goutham Harsha
tagline:      ":(){ :|: & };:"
baseurl:      ""
paginate:     5

# Permalinks
permalink:          pretty
relative_permalink: true

# About/contact
author:
  name:       Goutham Harsha
  url:        http://gouthams.space 

# Gems
gems:
  - jekyll-paginate
  - jemoji

#Others
markdown: kramdown
  